[package]
name = "rust_baseline"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tokenizers = "0.22.1"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "bert"
harness = false
