[package]
name = "rust_baseline"
version = "0.1.0"
edition = "2021"

[dependencies]
tokenizers = "0.19"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "bert"
harness = false
